name: Bug
description: Something does not work as expected
labels: ['type:bug']
body:
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual
    validations:
      required: true
  - type: dropdown
    id: where
    attributes:
      label: Where does it happen?
      options:
        - local
        - preview
        - production
    validations:
      required: true
